

const netherologist_shop_items = [
    'irons_spellbooks:fire_upgrade_orb',
    'irons_spellbooks:ice_upgrade_orb',
    'irons_spellbooks:lightning_upgrade_orb',
    'irons_spellbooks:holy_upgrade_orb',
    'irons_spellbooks:ender_upgrade_orb',
    'irons_spellbooks:blood_upgrade_orb',
    'irons_spellbooks:evocation_upgrade_orb',
    'irons_spellbooks:poison_upgrade_orb',
    'irons_spellbooks:mana_upgrade_orb',
    'irons_spellbooks:cooldown_upgrade_orb',
    'irons_spellbooks:protection_upgrade_orb',
]
const hunter_shop_items = [
    'backtobed:magical_returner',
    'sophisticatedbackpacks:backpack',
    'sophisticatedbackpacks:pickup_upgrade',
    'sophisticatedbackpacks:filter_upgrade',
    'sophisticatedbackpacks:magnet_upgrade',
    'sophisticatedbackpacks:feeding_upgrade',
    'sophisticatedbackpacks:compacting_upgrade',
    'sophisticatedbackpacks:void_upgrade',
    'sophisticatedbackpacks:restock_upgrade',
    'sophisticatedbackpacks:deposit_upgrade',
    'sophisticatedbackpacks:refill_upgrade',
    'sophisticatedbackpacks:inception_upgrade',
    'sophisticatedbackpacks:smelting_upgrade',
    'sophisticatedbackpacks:smoking_upgrade',
    'sophisticatedbackpacks:blasting_upgrade',
    'sophisticatedbackpacks:crafting_upgrade',
    'sophisticatedbackpacks:stack_upgrade_tier_1',      
    'sophisticatedbackpacks:tool_swapper_upgrade',
    'sophisticatedbackpacks:tank_upgrade',
    'sophisticatedbackpacks:battery_upgrade',
    'sophisticatedbackpacks:pump_upgrade',
    'sophisticatedbackpacks:upgrade_base',

]
const weaponsmith_shop_items = [
    'kubejs:rune_of_the_guardian',
    'kubejs:rune_of_the_battlemage',
    'kubejs:rune_of_the_summoner',
    'kubejs:rune_of_the_spellsword', 
    'kubejs:rune_of_the_kensei', 
    'kubejs:rune_of_the_berserker', 
    'kubejs:rune_of_the_head_hunter', 
    'kubejs:rune_of_the_alchemist',
    'kubejs:rune_of_the_duelist', 
    'kubejs:rune_of_the_druid', 
    'kubejs:rune_of_the_arcane_ranger',
    'kubejs:rune_of_the_explorer',

    'kubejs:gorilla_summoning_stone',
    'kubejs:grizzly_bear_summoning_stone',
    'kubejs:crow_summoning_stone',
    'kubejs:crocodile_summoning_stone',
    'kubejs:capuchin_monkey_summoning_stone',
    'kubejs:elephant_summoning_stone',
    'kubejs:komodo_dragon_summoning_stone',
    'kubejs:tarantula_hawk_summoning_stone',
    'kubejs:mantis_shrimp_summoning_stone',
    'kubejs:kangaroo_summoning_stone',
    'kubejs:bald_eagle_summoning_stone',
    'kubejs:sugar_glider_summoning_stone',
    'kubejs:mimic_octopus_summoning_stone',
    'kubejs:flutter_summoning_stone',

    'kubejs:warlock',
    'kubejs:engineer',
    'kubejs:warlord',
    'kubejs:scout',
    'kubejs:rogue',

    'kubejs:torn_page',
    'kubejs:subclass_skill_point',
    'kubejs:food_crate',
    'kubejs:evasion_elixir',
    'kubejs:speed_elixir',
    'kubejs:resistance_elixir',
    'kubejs:regeneration_elixir',
    'kubejs:shadow_form_elixir',
    'kubejs:strength_elixir',
    'kubejs:endurance_elixir',
    'kubejs:fire_elixir',
    'kubejs:absorption_elixir',
    'kubejs:charged_elixir',
    'kubejs:soul_steal_elixir',
    'kubejs:angel_wings_elixir',

]

const engineer_shop_items = [
    'create:shaft',
    'create:cogwheel',
    'create:large_cogwheel',
    'create:gearbox',
    'create:water_wheel',
    'create:large_water_wheel',
    'create:copper_valve_handle',
    'create:brass_hand',
    'create:whisk',
    'minecraft:andesite',
    'create:super_glue',
    'create:belt_connector',
    'create:crushed_raw_nickel',
    'create:crushed_raw_aluminium',
    'create:crushed_raw_iron',
    'create:crushed_raw_copper',
    'create:crushed_raw_zinc',
    'create:crushed_raw_platinum',
    'create:crushed_raw_silver',
    'create:crushed_raw_tin',
    'create:crushed_raw_lead',
    'create:brass_nugget',
    'create:zinc_nugget',
    'create:copper_nugget',
    'create:brass_ingot',
    'create:zinc_ingot',
    'create:andesite_alloy',
    'create:iron_sheet',
    'create:brass_sheet',
    'create:copper_sheet',
    'blocky_siege:bolt',
    'musketmod:cartridge',
    
    'crafting_on_a_stick:cartography_table',
    'minecraft:fire_charge',
    'minecraft:lever',

    'tetra:geode',
    'tetra:pristine_lapis',
    'tetra:pristine_emerald',
    'tetra:pristine_diamond'
]

const miner_shop_items = [
    
    'minecraft:coal_ore',
    'minecraft:deepslate_coal_ore',
    'minecraft:iron_ore',
    'minecraft:deepslate_iron_ore',
    'minecraft:copper_ore',
    'minecraft:deepslate_copper_ore',
    'minecraft:gold_ore',
    'minecraft:deepslate_gold_ore',
    'minecraft:redstone_ore',
    'minecraft:deepslate_redstone_ore',
    'minecraft:emerald_ore',
    'minecraft:deepslate_emerald_ore',
    'minecraft:lapis_ore',
    'minecraft:deepslate_lapis_ore',
    'minecraft:diamond_ore',
    'minecraft:deepslate_diamond_ore',
    'minecraft:nether_gold_ore',
    'minecraft:nether_quartz_ore',
    'epicsamurai:ruby_ore',
    'create:golden_sheet',
    'epicsamurai:jade_ore',
    'epicsamurai:deepslate_ruby_ore',
    'epicsamurai:deepslate_jade_ore',
    'epicsamurai:aquamarine_ore',
    'epicsamurai:deepslate_aquamarine_ore',
    'epicsamurai:onyx_ore',
    'epicsamurai:deepslate_onyx_ore',
    'epicsamurai:silver_ore',
    'epicsamurai:deepslate_silver_ore',
    'undead_revamp2:bostroxore',
    'echoing_expanse:deepslate_titanium_ore',
    'echoing_expanse:titanium_ore',
    'assortedcore:tin_ingot',
    'assortedcore:silver_ingot',
    'assortedcore:aluminum_ingot',
    'assortedcore:nickel_ingot',
    'assortedcore:platinum_ingot',
    'assortedcore:lead_ingot',
    'assortedcore:bronze_ingot',
    'assortedcore:electrum_ingot',
    'assortedcore:invar_ingot',
    'assortedcore:steel_ingot',
    'assortedcore:tin_nugget',
    'assortedcore:silver_nugget',
    'assortedcore:aluminum_nugget',          
    'assortedcore:nickel_nugget',
    'assortedcore:platinum_nugget',
    'assortedcore:lead_nugget',
    'assortedcore:bronze_nugget',
    'assortedcore:electrum_nugget',
    'assortedcore:invar_nugget',
    'assortedcore:steel_nugget',  
    'assortedcore:tin_dust',
    'assortedcore:copper_dust',
    'assortedcore:silver_dust',
    'assortedcore:aluminum_dust',          
    'assortedcore:nickel_dust',
    'assortedcore:platinum_dust',
    'assortedcore:lead_dust',
    'assortedcore:bronze_dust',
    'assortedcore:electrum_dust',
    'assortedcore:invar_dust',
    'assortedcore:steel_dust',
    'assortedcore:iron_dust',
    'assortedcore:gold_dust',
]

const wandering_trader_shop = [
    'relics:spatial_sign',
    'relics:reflection_necklace',
    'relics:magma_walker',
    'relics:aqua_walker',
    'relics:midnight_robe',
    'relics:drowned_belt',
    'relics:jellyfish_necklace',
    'relics:hunter_belt',
    'relics:rage_glove',
    'relics:ice_skates',
    'relics:bastion_ring',
    'relics:chorus_inhibitor',
    'relics:arrow_quiver',
    'relics:space_dissector',
    'relics:holy_locket',
    'relics:enders_hand',
    'relics:elytra_booster',
    'relics:magic_mirror',
    'relics:ice_breaker',
    'relics:blazing_flask',
    'relics:spore_sack',
    'relics:roller_skates',
    'relics:leather_belt',
    'vc_gliders:paraglider_wood',
    'artifacts:umbrella',
    'artifacts:flippers',
    'artifacts:everlasting_beef',
    'artifacts:eternal_steak',
    'artifacts:plastic_drinking_hat',
    'artifacts:novelty_drinking_hat',
    'artifacts:snorkel',
    'artifacts:night_vision_goggles',
    'artifacts:villager_hat',
    'artifacts:superstitious_hat',
    'artifacts:lucky_scarf',
    'artifacts:scarf_of_invisibility',
    'artifacts:cross_necklace',
    'artifacts:panic_necklace',
    'artifacts:shock_pendant',
    'artifacts:flame_pendant',
    'artifacts:thorn_pendant',
    'artifacts:charm_of_sinking',
    'artifacts:cloud_in_a_bottle',
    'artifacts:obsidian_skull',
    'artifacts:antidote_vessel',
    'artifacts:universal_attractor',
    'artifacts:crystal_heart',
    'artifacts:helium_flamingo',
    'artifacts:digging_claws',
    'artifacts:feral_claws',
    'artifacts:power_glove',
    'artifacts:fire_gauntlet',
    'artifacts:pocket_piston',
    'artifacts:vampiric_glove',
    'artifacts:golden_hook',
    'artifacts:aqua_dashers',
    'artifacts:bunny_hoppers',
    'artifacts:kitty_slippers',
    'artifacts:running_shoes',
    'artifacts:steadfast_spikes',
    'artifacts:whoopee_cushion',
    'relics:horse_flute',
    'relics:wool_mitten',
    'relics:amphibian_boot',
    'relics:researching_table',
    'grapplemod:grapplinghook',

]
//})


//    event.addTrade('armorer')
    

  //  event.addTrade('engineer')

    //event.addTrade

//})



